### ISSUE TITLE
peerinvalid Peer angular-material@1.1.3 wants angular@>=1.3 <1.6

### ISSUE THREAD

**Issue by conorliv** [mehmetbajin/gt-omscs#3]
This seems like a simple problem to solve, but I haven't used Node before. I also think having this documented might help someone else who tries to use this code who might run into the same issue.

Here is the error output when I run `npm install`
```
npm ERR! Darwin 16.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angular does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angular-material@1.1.3 wants angular@>=1.3 <1.6

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/main/gt-omscs/8803-1/final-project/npm-debug.log
```

Here's the `npm-debug.log` file:
```
0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'install' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose install where, deps [ '/Users/main/gt-omscs/8803-1/final-project',
4 verbose install   [ 'angular',
4 verbose install     'angular-animate',
4 verbose install     'angular-aria',
4 verbose install     'angular-material',
4 verbose install     'angular-material-icons',
4 verbose install     'angular-messages',
4 verbose install     'angular-ui-router',
4 verbose install     'express',
4 verbose install     'jquery',
4 verbose install     'lodash',
4 verbose install     'stats-lite' ] ]
5 verbose install where, peers [ '/Users/main/gt-omscs/8803-1/final-project', [] ]
6 info preinstall gatech-omscs-spring-2016-8803-1@1.0.0
7 verbose already installed skipping angular@^1.5.3 /Users/main/gt-omscs/8803-1/final-project
8 verbose already installed skipping angular-animate@^1.5.3 /Users/main/gt-omscs/8803-1/final-project
9 verbose already installed skipping angular-aria@^1.5.3 /Users/main/gt-omscs/8803-1/final-project
10 verbose already installed skipping angular-material@^1.0.6 /Users/main/gt-omscs/8803-1/final-project
11 verbose already installed skipping angular-material-icons@^0.7.0 /Users/main/gt-omscs/8803-1/final-project
12 verbose already installed skipping angular-messages@^1.5.3 /Users/main/gt-omscs/8803-1/final-project
13 verbose already installed skipping angular-ui-router@^0.2.18 /Users/main/gt-omscs/8803-1/final-project
14 verbose already installed skipping express@^4.13.4 /Users/main/gt-omscs/8803-1/final-project
15 verbose already installed skipping jquery@^2.2.2 /Users/main/gt-omscs/8803-1/final-project
16 verbose already installed skipping lodash@^4.7.0 /Users/main/gt-omscs/8803-1/final-project
17 verbose already installed skipping stats-lite@^2.0.1 /Users/main/gt-omscs/8803-1/final-project
18 silly install resolved []
19 info build /Users/main/gt-omscs/8803-1/final-project
20 verbose linkStuff [ false, false, false, '/Users/main/gt-omscs/8803-1' ]
21 info linkStuff gatech-omscs-spring-2016-8803-1@1.0.0
22 verbose linkBins gatech-omscs-spring-2016-8803-1@1.0.0
23 verbose linkMans gatech-omscs-spring-2016-8803-1@1.0.0
24 verbose rebuildBundles gatech-omscs-spring-2016-8803-1@1.0.0
25 verbose rebuildBundles [ 'angular',
25 verbose rebuildBundles   'angular-animate',
25 verbose rebuildBundles   'angular-aria',
25 verbose rebuildBundles   'angular-material',
25 verbose rebuildBundles   'angular-material-icons',
25 verbose rebuildBundles   'angular-messages',
25 verbose rebuildBundles   'angular-ui-router',
25 verbose rebuildBundles   'express',
25 verbose rebuildBundles   'jquery',
25 verbose rebuildBundles   'lodash',
25 verbose rebuildBundles   'stats-lite' ]
26 info install gatech-omscs-spring-2016-8803-1@1.0.0
27 info postinstall gatech-omscs-spring-2016-8803-1@1.0.0
28 info prepublish gatech-omscs-spring-2016-8803-1@1.0.0
29 verbose stack Error: The package angular does not satisfy its siblings' peerDependencies requirements!
29 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:103:32
29 verbose stack     at /usr/local/lib/node_modules/npm/lib/install.js:225:5
29 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
29 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
29 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
29 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
29 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
29 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
29 verbose stack     at cb (/usr/local/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
29 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
30 verbose cwd /Users/main/gt-omscs/8803-1/final-project
31 error Darwin 16.4.0
32 error argv "node" "/usr/local/bin/npm" "install"
33 error node v0.12.0
34 error npm  v2.5.1
35 error code EPEERINVALID
36 error peerinvalid The package angular does not satisfy its siblings' peerDependencies requirements!
36 error peerinvalid Peer angular-material@1.1.3 wants angular@>=1.3 <1.6
37 verbose exit [ 1, true ]
```

**Comment by mehmetbajin** [comment]
Please upgrade your version of `node` to at least `v7` and `npm` to at least `v4`. You can use [n](https://www.npmjs.com/package/n) to do this.
